apiVersion: v1
kind: ReplicationController
metadata:
  name: uploadimages-server 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: uploadimages
    spec:
      containers:
      - name: upload-images-server
        image: jdmaster/server-upload-images
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000