apiVersion: v1
kind: ReplicationController
metadata:
  name: uploadimages-cli
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: uploadimages
    spec:
      containers:
      - name: upload-images-client
        image: jdmaster/client-upload-images:5f368f0b360c0e53369690421f4310c12bc9f46a
        env:
        - name: REACT_APP_HOST_PROTOCOL
          value: "http"
        - name: REACT_APP_HOST_SERVER
          value: "34.66.128.97"
        - name: REACT_APP_PORT_SERVER
          value: "5000"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000