apiVersion: v1
kind: Service
metadata:
  name: uploadimages-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http5000
  selector:
    role: uploadimages

