on: push
name: deploy
jobs:
  build-and-push:
    name: build and push images SERVER and CLIENT
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push to docker SERVER
      uses: docker/build-push-action@v2
      with:
        context: server
        repository: ${{ github.repository }}
        push: true
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    - name: build and push to docker CLIENT
      uses: docker/build-push-action@v2
      with:
        context: client
        repository: ${{ github.repository }}
        push: true
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
