name: deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push:
    name: build and push images SERVER and CLIENT
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: build and push SERVER
      uses: docker/build-push-action@v2
      with:
        context: server
        repository: ${{ github.repository }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/server-upload-images:${{ github.sha }}
    -
      name: build and push CLIENT
      uses: docker/build-push-action@v2
      with:
        context: client
        repository: ${{ github.repository }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/client-upload-images:${{ github.sha }}
