name: deploy
on:
  push:
    branches:
      - 'main'
jobs:    
  push-server:
    name: Push server in docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: build and push server
      uses: docker/build-push-action@v2
      with:
        context: server
        tags: ${{ secrets.DOCKER_USERNAME }}/server-upload-images:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/server-upload-images:latest
        push: true
  push-cli:
    name: Push client in docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: build and push CLIENT
      uses: docker/build-push-action@v2
      with:
        context: client
        tags: ${{ secrets.DOCKER_USERNAME }}/client-upload-images:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/client-upload-images:latest
        push: true
  kube:
    needs: [push-server, push-cli]
    name: Actualizar pods kubernetes
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: login en kube
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: cluster-1
        location: us-central1-c
        credentials: ${{ secrets.gcp_credentials }}
    - 
      name: Actualizar imagen en kube
      #run: cd kubernetes && kubectl -n devops apply -f controler-server.yaml && kubectl -n devops apply -f controler-client.yaml
      run : kubectl -n devops set image --record deployment.apps/uploadimages-server-deploy upload-images-server=jdmaster/server-upload-images:${{ github.sha }} && kubectl -n devops set image --record replicationcontroller/uploadimages-cli upload-images-client=jdmaster/client-upload-images:${{ github.sha }}