name: deploy
on:
  push:
    branches:
      - 'main'
jobs:    
  push-server:
    name: build and push SERVER in docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: build and push SERVER
      uses: docker/build-push-action@v2
      with:
        context: server
        tags: ${{ secrets.DOCKER_USERNAME }}/server-upload-images:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/server-upload-images:latest
        push: true
  push-cli:
    name: build and push Client in docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: build and push CLIENT
      uses: docker/build-push-action@v2
      with:
        context: client
        tags: ${{ secrets.DOCKER_USERNAME }}/client-upload-images:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/client-upload-images:latest
        push: true
  kube:
    name: build and push SERVER in docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: get-credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: cluster-1
        location: us-central1-c
        credentials: ${{ secrets.gcp_credentials }}
    - 
      name: get-pods
      run: cd kubernetes && kubectl -n devops apply -f controler-server.yaml && kubectl -n devops apply -f controler-client.yaml
